a=input ("ism")
b=input("vil")
c=input("tum")
x=input("mah")
s=input("ko'cha")
a=a.capitalize()
b=b.capitalize()
c=c.capitalize()
x=x.capitalize()
s=s.capitalize()
print( "xurmatli a siz [b] viloyatning [c] tumaniga qarashli [x] mahallaning [s] ko'chasida yashaysiz")